name: push to AWS S3
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  push to s3:
    runs-on: ubuntu-latest
    steps:
      
       - name: Check out repository code
        uses: actions/checkout@v4
        name: npm install
        name: npm run build
        run: npm run build
        -name: list the directories
          run: ls
